# Generated by Django 3.2.9 on 2022-01-21 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtuApp', '0002_alter_mycontacts_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('plan', models.CharField(max_length=20, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
