# Generated by Django 3.2.9 on 2022-01-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0007_alter_topuphistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycontacts',
            old_name='contacts',
            new_name='contact',
        ),
    ]
