# Generated by Django 3.2.9 on 2022-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0009_alter_mycontacts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuphistory',
            name='plan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
