# Generated by Django 3.2.9 on 2022-01-22 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vtuApp', '0010_alter_topuphistory_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResellPrices',
            new_name='UserType',
        ),
    ]
