# Generated by Django 3.2.9 on 2022-02-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0011_rename_resellprices_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CgWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_balance', models.FloatField(blank=True, max_length=200, null=True)),
                ('network', models.CharField(blank=True, choices=[('12', 'mtn'), ('9', '9mobile'), ('8', 'airtel'), ('7', 'glo')], max_length=200, null=True)),
                ('val', models.CharField(blank=True, default='MB', max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
