# Generated by Django 3.2.9 on 2022-02-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0012_cgwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='gifted',
            field=models.BooleanField(default=True),
        ),
    ]
