# Generated by Django 3.2.9 on 2022-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtuApp', '0013_usertype_gifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='percent',
            field=models.IntegerField(default=25),
        ),
    ]
