# Generated by Django 3.2.6 on 2021-12-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalFundingToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('user_account_number', models.FloatField(default=0)),
                ('get_first_deposit', models.BooleanField(blank=True, default=False, null=True)),
                ('testified', models.BooleanField(blank=True, default=False, null=True)),
                ('to_cash_out', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('read_item', 'Can read item'),),
            },
        ),
        migrations.CreateModel(
            name='WithdrawReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default=0, max_length=200)),
                ('account_number', models.CharField(default=0, max_length=200)),
                ('beneficiary', models.CharField(default=0, max_length=200)),
                ('bank_name', models.CharField(default=0, max_length=200)),
                ('bank_code', models.CharField(default=0, max_length=200)),
                ('time_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userwallet.userwallet')),
            ],
            options={
                'ordering': ['-time_updated'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='0000', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=0, max_length=20)),
                ('tx_ref', models.CharField(default=0, max_length=6)),
                ('type', models.CharField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit')], max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=12)),
                ('account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=200, null=True)),
                ('stamp_charge', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userwallet.userwallet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
