# Generated by Django 3.2.6 on 2021-12-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('platinum', 'platinum'), ('steel', 'steel'), ('silver', 'silver'), ('gold', 'gold'), ('ruby', 'ruby'), ('diamond', 'diamond'), ('obsidian', 'obsidian')], default='standard', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('daily_earn', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_earn', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('ref_earning', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('contract_period', models.CharField(default='4', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Subscibers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_left', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('subscribed_date', models.DateField(default=django.utils.timezone.now)),
                ('next_run_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ended', 'ended'), ('active', 'active')], default='active', max_length=20)),
                ('miss', models.IntegerField(default=0)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packages')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-next_run_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_line', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(default='image', max_length=200)),
                ('images', models.FileField(blank=True, null=True, upload_to='media/post/2021-12-09')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/post/2021-12-09')),
                ('content', models.TextField(max_length=3000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('count_activities', models.IntegerField(default=0)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packages')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('like', models.BooleanField(default=0)),
                ('comment', models.TextField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.personalinfomation')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
