# Generated by Django 3.2.9 on 2022-01-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={},
        ),
        migrations.RemoveField(
            model_name='packages',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='daily_earn',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='ref_earning',
        ),
        migrations.AddField(
            model_name='packages',
            name='daily_sales',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='contract_period',
            field=models.CharField(default='7', max_length=200),
        ),
        migrations.AlterField(
            model_name='packages',
            name='plan',
            field=models.CharField(choices=[('5000', '5000'), ('15000', '15000'), ('20000', '20000'), ('25000', '25000'), ('30000', '30000'), ('45000', '45000'), ('50000', '5000'), ('100000', '100000'), ('200000', '200000'), ('300000', '300000'), ('400000', '400000'), ('500000', '500000')], default='5000', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='media/post/2022-01-14'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/post/2022-01-14'),
        ),
    ]
