# Generated by Django 3.2.9 on 2022-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220115_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='status',
            field=models.CharField(choices=[('bought', 'bought'), ('active', 'active'), ('ended', 'ended')], default='bought', max_length=20),
        ),
    ]
