# Generated by Django 3.2.9 on 2022-02-02 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20220201_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_left', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('subscribed_date', models.DateField(default=django.utils.timezone.now)),
                ('next_run_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('ended', 'ended')], default='bought', max_length=20)),
                ('earn_after', models.CharField(choices=[('24', 'Every 24 hrs'), ('48', 'Every 48 hrs'), ('4days', 'After 4 days')], default='Every 24 hrs', max_length=20)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-next_run_date'],
            },
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='daily_sales',
            new_name='daily_earn',
        ),
        migrations.AlterField(
            model_name='packages',
            name='plan',
            field=models.CharField(choices=[('0.1GS', '2000'), ('0.2GS', '5000')], default='0.1GS', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='media/post/2022-02-02'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/post/2022-02-02'),
        ),
        migrations.DeleteModel(
            name='Shares',
        ),
        migrations.AddField(
            model_name='usergold',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packages'),
        ),
        migrations.AddField(
            model_name='usergold',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
