# Generated by Django 3.2.9 on 2022-02-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220202_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergold',
            name='state',
            field=models.CharField(choices=[('awaiting payment', 'awaiting payment'), ('awaiting approval', 'awaiting approval')], default='awaiting payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='usergold',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('ended', 'ended')], default='pending', max_length=20),
        ),
    ]
