# Generated by Django 3.2.9 on 2022-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220202_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergold',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='goldstock/userproof/2022-02-02'),
        ),
        migrations.AlterField(
            model_name='usergold',
            name='state',
            field=models.CharField(choices=[('awaiting payment', 'awaiting payment'), ('awaiting approval', 'awaiting approval'), ('approved', 'approved')], default='awaiting payment', max_length=20),
        ),
    ]
