# Generated by Django 3.2.9 on 2022-02-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220207_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='daily_earn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
