# Generated by Django 3.2.9 on 2022-02-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220210_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergold',
            name='proof_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
