# Generated by Django 4.0.3 on 2022-04-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_post_images_alter_post_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='media/post/2022-04-19'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/post/2022-04-19'),
        ),
        migrations.AlterField(
            model_name='usergold',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='goldstock/userproof/2022-04-19'),
        ),
    ]
