"""
Django settings for coinsproject project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os, django_heroku, socket, psycopg2
from local_settings import environment
import requests

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'secure222-lrtzqrwm24znf%t=syya21w%onv#4(2-!qgx4-0plc&2$!lmxi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
#
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True

ALLOWED_HOSTS = [

]

ADMINS = [
    ('wusetech@gmail.com'),
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'user',
    'userwallet',
    'referral',
    'myadmin',
    #'vtuApp',
    'six',
    'preventconcurrentlogins',
    'django.contrib.humanize',
]

AUTH_USER_MODEL = 'user.MyUser'
CSRF_FAILURE_VIEW = 'user.views.csrf_failure'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'preventconcurrentlogins.middleware.PreventConcurrentLoginsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'localProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'context_processors.global_variable',

            ],
        },
    },
]

WSGI_APPLICATION = 'localProject.wsgi.application'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': str(BASE_DIR / 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd38c9ghunfn5jd',
        'USER': 'ppxgephquufmqe',
        'PASSWORD': '4f7218bf206811642830b1762a98d81733b1fbf064676a9e2f9734235af72a1f',
        'HOST': 'ec2-34-231-63-30.compute-1.amazonaws.com',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'

AWS_ACCESS_KEY_ID = 'AKIASECCF5ETZBMRYYQW'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'peektop'
AWS_QUERYSTRING_AUTH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATIC_URL = os.environ.get('EDGE_URL', '') + '/static/'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#gmail_send/settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = 'zpxbkfmhqqxbfzte' #past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True
LOGIN_URL = '/login'


#DJANGORESIZED_DEFAULT_SIZE = [1920, 1080]
DJANGORESIZED_DEFAULT_QUALITY = 75
DJANGORESIZED_DEFAULT_KEEP_META = True
DJANGORESIZED_DEFAULT_FORCE_FORMAT = 'JPEG'
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {'JPEG': ".jpg"}
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = True

SESSION_EXPIRE_SECONDS = 3600
SESSION_COOKIE_SECURE = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_TIMEOUT_REDIRECT = 'localProject:welcome'


SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SAMESITE = 'Strict'
SECURE_HSTS_SECONDS = 15768000  # set low, but when site is ready for deployment, set to at least 15768000 (6 months)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


"""
PAYMENT GATEWAY
Dreambigxz1
"""
#Test key1
# FLUTTER_WAVE_SECRET_KEY = 'Bearer FLWSECK_TEST-a8e4e10033ed523390c9f839d2214509-X'
# FLUTTER_WAVE_PUB_KEY = 'FLWPUBK_TEST-ad745b9b6ef96bf9f1b2834ac7fbc73a-X'
#

FLUTTER_WAVE_SECRET_KEY = 'Bearer FLWSECK-57a84df4e349f4b72ffd4a98688a47fb-X'
FLUTTER_WAVE_PUB_KEY = 'FLWPUBK-ed50770f95c8cdcb56a16706cd8d673d-X'

# FLUTTER WAVE 2
FLUTTER_WAVE_SECRET_KEY2 = 'Bearer FLWSECK-052afce2c8c5fc62ade045c209625092-X'
FLUTTER_WAVE_PUB_KEY2 = 'FLWPUBK-224f319c4bb74e4dc0583915383ec5d5-X'

COINBASE_SECRET_KEY = 'f0d058d1-01da-4e50-a519-c0a217cea842'
FLUTTER_WAVE_HASH_KEY = 'HASH_HASH_HASH%%%%%%%%%akjbsjbkawbjABAnaaGFSXQRSDWQTJHJ'


#donyemordi
MAIL_JET_API_KEY = '32d3ccc9673f50deea2fbd0e031f924a'
MAIL_JET_API_SECRET_KEY = '6a1d73ab741ccd1ddbc98c52e8d6f9d4'

#emonney1
MAIL_JET_API_KEY_1 = '6048d7418e2acf5e922913aee9bade34'
MAIL_JET_API_SECRET_1 = 'd1a0c86713851a4fa085250ee7b673b7'

#emonney2
MAIL_JET_API_KEY_CREDIT = 'e6744680ef46b2ce604f9f841e20d183'
MAIL_JET_API_SECRET_KEY_CREDIT = 'b182912d734eb77e94c8521c32e97278'

EMAIL_DELIVERY = 'noreply@peektop.com'

django_heroku.settings(locals())

"""


"""
