# Generated by Django 3.2.6 on 2021-12-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Kuda Micro Finance Bank', max_length=200)),
                ('account_number', models.CharField(default='2003094297', max_length=20)),
                ('account_name', models.CharField(default='Olufemi Ilori', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('tot_users', models.IntegerField(default=200)),
                ('avg_traders', models.IntegerField(default=400)),
                ('total_transaction', models.DecimalField(decimal_places=2, default=7000, max_digits=50)),
                ('bill_settlement', models.DecimalField(decimal_places=2, default=7000, max_digits=50)),
                ('total_traded', models.DecimalField(decimal_places=2, default=7000, max_digits=50)),
                ('total_trade_return', models.DecimalField(decimal_places=2, default=7000, max_digits=50)),
                ('total_sent_to_flutter_wave', models.DecimalField(decimal_places=2, default=7000, max_digits=50)),
                ('total_available_balance', models.DecimalField(decimal_places=2, default=7000, max_digits=50)),
                ('site_name', models.CharField(default='Doughscoin Limited', max_length=200)),
                ('site_url', models.CharField(default='doughscoin.com', max_length=200)),
                ('phone_number', models.CharField(default='+1 (610) 215‑9003', max_length=200)),
                ('email', models.CharField(default='support@doughscoin.com', max_length=200)),
                ('site_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
