# Generated by Django 3.2.9 on 2022-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='available_message',
            field=models.CharField(default='Your registrations in GS is Successful,\n\nkindly login to your account and purchase SG gold of your choice', max_length=200),
        ),
        migrations.AddField(
            model_name='administration',
            name='market_message',
            field=models.CharField(default='Market currently closed, please come back 9am', max_length=200),
        ),
        migrations.AddField(
            model_name='administration',
            name='not_available_message',
            field=models.CharField(default='Your registrations in GS is Successful.\n\nMarket currently closed, please come back 9am', max_length=200),
        ),
    ]
