# Generated by Django 3.2.9 on 2022-02-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20220204_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='live_bot',
            field=models.BooleanField(default=True),
        ),
    ]
