# Generated by Django 3.2.9 on 2022-02-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_administration_live_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='available_message',
            field=models.TextField(default='Your registrations in GS is Successful,\n\nkindly login to your account and purchase SG gold of your choice'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='not_available_message',
            field=models.TextField(default='Your registrations in GS is Successful.\n\nMarket currently closed, please come back 9am'),
        ),
    ]
