# Generated by Django 3.2.9 on 2022-02-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='read',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.AddField(
            model_name='messages',
            name='first_save',
            field=models.BooleanField(default=True),
        ),
    ]
