# Generated by Django 3.2.9 on 2022-02-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20220206_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='messages',
        ),
    ]
