# Generated by Django 3.2.9 on 2022-02-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_rename_message_messages_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='mess',
        ),
    ]
