# Generated by Django 3.2.9 on 2022-02-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_rename_messages_messages_mess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='AdminMessage',
        ),
    ]
