# Generated by Django 3.2.9 on 2022-02-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_rename_messages_adminmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminMessage',
        ),
    ]
