# Generated by Django 3.2.9 on 2022-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_administration_data_gifting'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='flutter_wave',
            field=models.CharField(choices=[('others', 'others'), ('nexzus', 'nexzus')], default='others', max_length=20),
        ),
    ]
