# Generated by Django 3.2.9 on 2022-01-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='count_login',
            field=models.IntegerField(default=0),
        ),
    ]
