# Generated by Django 3.2.9 on 2022-02-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_count_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='read_message',
            field=models.BooleanField(default=False),
        ),
    ]
