# Generated by Django 4.0.3 on 2022-04-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='top_admin',
            field=models.BooleanField(default=False),
        ),
    ]
